a = 3
b = 6
c = 5

add = a+b
print("add",type(add))
print("add----------------------------",add)

sub = a-b
print("sub",type(sub))
print("sub",sub)

mul = a*b
print("mul",type(mul))
print("mul",mul)

div = b/a
print("div",type(div))
print("div",div)

mod = c%a
print("mod",type(mod))
print("mod",mod)


pow = c**a
print("pow",type(pow))
print("pow",pow)

floor_div = c//a
print("floor_div",type(floor_div))
print("floor_div",floor_div)  # floor division

