x = 10

if x > 5:
    print("X is greater than 5")
if x < 11:
    print("X is less than 11")
if x >= 10:
    print("X is greater than or equal to 10")
if x <= 10:
    print("X is less than or equal to 10")
if x == 10:
    print("X is 10")
if x != 5:
    print("X is not 5")
if x != 5:  # 'x <> 5' is invalid in Python, so we use 'x != 5'
    print("X is not 5 at all")
if x is 10:
    print("YES, X is 10")
if x is not 11:
    print("NO, X is not 11")
